<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <RootNamespace>TelegramBotPlatform.UnitTests</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TelegramBotPlatform.Application\TelegramBotPlatform.Application.csproj" />
      <ProjectReference Include="..\TelegramBotPlatform.Infrastructure\TelegramBotPlatform.Infrastructure.csproj" />
      <ProjectReference Include="..\TelegramBotPlatform.Persistence\TelegramBotPlatform.Persistence.csproj" />
    </ItemGroup>

</Project>
