global using System.ComponentModel.DataAnnotations;
global using FluentResults;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using TelegramBotPlatform.Persistence.Entities;
global using TelegramBotPlatform.Persistence.Repositories;
global using TelegramBotPlatform.Public.Bots;